// no-coauthor — denies a `git commit` whose MESSAGE carries an AI/agent attribution
// (Co-Authored-By, Claude-Session, "Generated with Claude"), and a delegation prompt that
// orders one. The message is what the commit will record: -m values, a heredoc body,
// --trailer values and a -F file read from the project. Only a command segment that RUNS git
// commit counts (a `git log | grep Co-Authored-By` is not one). Deliberate limit: a message
// built from a substitution (`-m "$(cat msg)"`) cannot be read without running it.

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { projectRootOf } from '../../lib/config.mjs';
import { hasRealCommandIntent } from '../../lib/delegation.mjs';
import {
  commitMessageOf,
  isDryRunCommit,
  isGitCommit,
  normalizeGitCommand,
} from '../../lib/git.mjs';
import {
  compileRegexList,
  delegationPromptOf,
  deny,
  runGate,
  shellCommandOf,
  toolInGroups,
} from '../../lib/hook-io.mjs';

const GATE_ID = 'no-coauthor';
const CONFIG_KEY = 'blockCoauthorTrailers';

// Narrow on purpose: "generated by vitest" or "usage with Claude Code" in a subject line is
// not an attribution; a trailer or a "generated with/by <an agent>" phrase is.
const DEFAULT_ATTRIBUTION_PATTERNS = [
  String.raw`co-authored-by\s*[:=]`,
  String.raw`claude-session:`,
  String.raw`assisted-by:`,
  String.raw`authored-with:`,
  String.raw`generated (?:with|by) (?:claude|ai|copilot|codex|cursor|gemini|chatgpt|an? (?:ai|llm|assistant)|a (?:bot|model))\b`,
  String.raw`🤖 generated`,
];

const DEFAULT_ESCAPE_HATCH = '[allow-coauthor]';

// ── The commit segment ──────────────────────────────────────────────────────────────
const SEGMENT_SEPARATOR = /;|&&|\|\||\||\n/;
const ARGUMENT_PATTERN = /"([^"]*)"|'([^']*)'|(\S+)/g;
const GIT_BINARY_TOKEN = /(?:^|[\\/])git(?:\.exe)?$/i;
const WRAPPER_TOKEN = /^(?:\w+=\S*|command|sudo|env)$/i;

function runsGit(segment) {
  const tokens = [];
  for (const match of segment.matchAll(ARGUMENT_PATTERN))
    tokens.push(match[1] ?? match[2] ?? match[3]);
  while (tokens.length > 0 && WRAPPER_TOKEN.test(tokens[0])) tokens.shift();
  return tokens.length > 0 && GIT_BINARY_TOKEN.test(tokens[0]);
}

// A heredoc body spans lines, so the command is split only after the segment that opens it
// has been recognized on its first line.
function runsRealCommit(command) {
  return String(command)
    .split(SEGMENT_SEPARATOR)
    .some((segment) => {
      if (!runsGit(segment)) return false;
      const normalized = normalizeGitCommand(segment);
      return isGitCommit(normalized) && !isDryRunCommit(normalized);
    });
}

function fileReader(root) {
  return (path) => {
    const resolved = resolve(root, path);
    try {
      return existsSync(resolved) ? readFileSync(resolved, 'utf8') : '';
    } catch {
      return '';
    }
  };
}

function firstMatch(text, patterns) {
  for (const pattern of patterns) {
    const match = pattern.exec(text);
    if (match) return match[0];
  }
  return null;
}

function denyAttribution(matched, escapeHatch) {
  deny(
    CONFIG_KEY,
    `This commit message carries an AI/agent attribution ("${matched}"). Remove it — no ` +
      'Co-Authored-By, no "Generated with", no session trailer. If this commit legitimately ' +
      `must keep a co-author (e.g. importing external history), add "${escapeHatch}" to the ` +
      `command to allow it once, or set attributionPatterns under ${CONFIG_KEY} in .ai/config.json.`,
  );
}

function checkDelegationPrompt(prompt, patterns, escapeHatch) {
  if (escapeHatch && prompt.includes(escapeHatch)) return;
  const ordered = patterns.find((pattern) =>
    hasRealCommandIntent(prompt, pattern),
  );
  if (ordered) denyAttribution(ordered.exec(prompt)[0], escapeHatch);
}

function checkShellCommand(command, patterns, escapeHatch, root) {
  if (!runsRealCommit(command)) return;
  if (escapeHatch && command.includes(escapeHatch)) return;
  const message = commitMessageOf(command, { readFile: fileReader(root) });
  const matched = firstMatch(message, patterns);
  if (matched) denyAttribution(matched, escapeHatch);
}

runGate(
  {
    id: GATE_ID,
    configKey: CONFIG_KEY,
    enabledByDefault: true,
    defaultParams: {
      attributionPatterns: DEFAULT_ATTRIBUTION_PATTERNS,
      escapeHatch: DEFAULT_ESCAPE_HATCH,
    },
  },
  ({ toolName, toolInput, parameters, cwd }) => {
    const isShell = toolInGroups(toolName, ['shell']);
    if (!isShell && !toolInGroups(toolName, ['delegation'])) return;

    const escapeHatch = String(parameters.escapeHatch ?? '');
    const { patterns } = compileRegexList(parameters.attributionPatterns);
    if (patterns.length === 0) return;

    if (isShell) {
      checkShellCommand(
        shellCommandOf(toolInput),
        patterns,
        escapeHatch,
        projectRootOf(cwd) ?? cwd,
      );
    } else {
      checkDelegationPrompt(
        delegationPromptOf(toolInput),
        patterns,
        escapeHatch,
      );
    }
  },
);
