// no-coauthor — denies a `git commit` that carries an AI/agent attribution trailer
// (Co-Authored-By, "Generated with", "Claude-Session", and the like). The defect is fully
// visible in the command text the tool is about to run, so this is a deterministic deny with
// an escape hatch, never a prose reminder: the offending trailer is right there to point at.
//
// justification: no existing gate covers this. bash-commands denies destructive commands and
// block-remote-publish denies pushes; neither inspects the commit MESSAGE for attribution.
// lint-commit runs the linter on a commit but never reads the message text. This is the first
// gate that reads what a commit says, not just that it is a commit.
//
// ── What a project can configure (params) ───────────────────────────────────────────
//   attributionPatterns  regex sources (matched case-insensitively) of trailers/phrases
//                        that must not appear in a commit message. Replaces the built-in
//                        list wholesale, so a project that wants a different policy states
//                        its full list.
//   escapeHatch          a substring the author can put in the command to bypass this gate
//                        for one legitimate commit (e.g. importing external history that
//                        genuinely carries a co-author). Default '[allow-coauthor]'.
//
// ── How it detects a commit and reads its message ────────────────────────────────────
// Reuses lint-commit's git-global-option normalization so `git -C /repo -c x=y commit` is
// recognized as a commit. It then scans the WHOLE command text (which contains the -m value
// or the heredoc body) for any attribution pattern — this over-includes on purpose (a match
// inside an unrelated string is a rare false block the author clears with the escape hatch)
// rather than under-includes (a real trailer slipping through in a shape we did not parse).
//
// ── Fail-safe shape ──────────────────────────────────────────────────────────────────
// Not a commit: allow (silent). A commit with no attribution pattern: allow. A commit whose
// text matches a pattern and does NOT contain the escape hatch: deny, naming the match.

import { runGate, deny, toolInGroups } from '../../lib/hook-io.mjs';

const GATE_ID = 'no-coauthor';
const CONFIG_KEY = 'blockCoauthorTrailers';

const SHELL_GROUPS = ['shell', 'delegation'];

// Attribution trailers/phrases an AI agent tends to append. Sources, compiled case-insensitively.
const DEFAULT_ATTRIBUTION_PATTERNS = [
  String.raw`co-authored-by:`,
  String.raw`generated with`,
  String.raw`generated by`,
  String.raw`🤖 generated`,
  String.raw`claude-session:`,
  String.raw`assisted-by:`,
  String.raw`authored-with:`,
  String.raw`with claude code`,
];

const DEFAULT_ESCAPE_HATCH = '[allow-coauthor]';

// One global git option at a time, stripped repeatedly — same normalization lint-commit and
// bash-commands use, so `git -C /repo -c x=y commit` reduces to `git commit` before matching.
const GIT_OPTION_WITH_VALUE = String.raw`(?:-[Cc]|--git-dir|--work-tree|--namespace|--exec-path|--config-env)(?:\s+|=)\S+`;
const GIT_FLAG_OPTION = String.raw`--(?:paginate|no-pager|bare|no-optional-locks)|-p`;
const GIT_GLOBAL_OPTION_PATTERN = new RegExp(
  String.raw`\bgit\s+(?:${GIT_OPTION_WITH_VALUE}|${GIT_FLAG_OPTION})\s+`,
  'i',
);
const GIT_COMMIT_PATTERN = /\bgit\s+commit\b/i;

function normalizeGitOptions(command) {
  let previous;
  let normalized = command;
  do {
    previous = normalized;
    normalized = normalized.replace(GIT_GLOBAL_OPTION_PATTERN, 'git ');
  } while (normalized !== previous);
  return normalized;
}

function isGitCommit(command) {
  return GIT_COMMIT_PATTERN.test(normalizeGitOptions(command));
}

function commandTextFrom(toolInput) {
  return String(toolInput.CommandLine ?? toolInput.command ?? '');
}

/** The first attribution pattern the command text matches, or null when none does. */
function matchedAttribution(command, attributionPatterns) {
  for (const source of attributionPatterns) {
    let pattern;
    try {
      pattern = new RegExp(source, 'i');
    } catch {
      // A malformed override pattern is skipped rather than crashing the gate; the rest of
      // the list still protects.
      continue;
    }
    if (pattern.test(command)) return source;
  }
  return null;
}

runGate(
  {
    id: GATE_ID,
    configKey: CONFIG_KEY,
    enabledByDefault: true,
    defaultParams: {
      attributionPatterns: DEFAULT_ATTRIBUTION_PATTERNS,
      escapeHatch: DEFAULT_ESCAPE_HATCH,
    },
  },
  ({ toolName, toolInput, parameters }) => {
    if (!toolInGroups(toolName, SHELL_GROUPS)) return;

    const command = commandTextFrom(toolInput);
    if (!isGitCommit(command)) return;

    const escapeHatch = parameters.escapeHatch ?? DEFAULT_ESCAPE_HATCH;
    if (escapeHatch && command.includes(escapeHatch)) return;

    const match = matchedAttribution(command, parameters.attributionPatterns);
    if (!match) return;

    deny(
      CONFIG_KEY,
      `This commit message carries an AI/agent attribution trailer (matched "${match}"). ` +
        'Remove it — no Co-Authored-By, no "Generated with", no session trailer. If this ' +
        `commit legitimately must keep a co-author (e.g. importing external history), add ` +
        `"${escapeHatch}" to the command to allow it once, or set attributionPatterns/` +
        'blockCoauthorTrailers in .ai/config.json.',
    );
  },
);
