import assert from 'node:assert/strict';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import {
  bash,
  delegate,
  isDeny,
  makeProject,
  messageOf,
  runGateProcess,
} from '../../lib/testing.mjs';

const GATE = join(dirname(fileURLToPath(import.meta.url)), 'index.mjs');

function runGate(payload, options) {
  return runGateProcess(GATE, payload, options);
}

const commit = bash;

test('DENIES a commit carrying Co-Authored-By', () => {
  assert.ok(
    isDeny(
      runGate(
        commit(
          'git commit -m "fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>"',
        ),
      ),
    ),
  );
});

test('DENIES a commit carrying a Generated-with / session trailer', () => {
  assert.ok(
    isDeny(
      runGate(
        commit('git commit -m "feat: x\n\n🤖 Generated with Claude Code"'),
      ),
    ),
  );
  assert.ok(
    isDeny(
      runGate(
        commit(
          'git commit -m "feat: x\n\nClaude-Session: https://claude.ai/x"',
        ),
      ),
    ),
  );
});

test('DENIES the trailer through a global-option prefixed commit', () => {
  assert.ok(
    isDeny(
      runGate(
        commit('git -C /repo commit -m "x\n\nCo-Authored-By: A <a@b.c>"'),
      ),
    ),
  );
});

test('allows a clean commit message', () => {
  assert.equal(runGate(commit('git commit -m "fix: a real fix"')), null);
});

test('allows a non-commit command that merely mentions co-author', () => {
  assert.equal(
    runGate(commit('git log --format=%b | grep "Co-Authored-By:"')),
    null,
  );
});

test('escape hatch: the marker in the command allows one legitimate co-author', () => {
  assert.equal(
    runGate(
      commit(
        'git commit -m "import history\n\nCo-Authored-By: A <a@b.c>" [allow-coauthor]',
      ),
    ),
    null,
  );
});

test('disabled by config: the gate does not run', () => {
  assert.equal(
    runGate(commit('git commit -m "x\n\nCo-Authored-By: A <a@b.c>"'), {
      config: { gates: { blockCoauthorTrailers: false } },
    }),
    null,
  );
});

test('project attributionPatterns override replaces the built-in list', () => {
  const config = {
    gates: {
      blockCoauthorTrailers: {
        enabled: true,
        attributionPatterns: ['signed-off-by:'],
      },
    },
  };
  assert.equal(
    runGate(commit('git commit -m "x\n\nCo-Authored-By: A <a@b.c>"'), {
      config,
    }),
    null,
  );
  assert.ok(
    isDeny(
      runGate(commit('git commit -m "x\n\nSigned-off-by: A <a@b.c>"'), {
        config,
      }),
    ),
  );
});

// ── Regressions from the audit ──────────────────────────────────────────────────────

test('a delegation prompt that orders an attribution trailer is denied; one that forbids it is allowed', () => {
  assert.ok(
    isDeny(
      runGate(
        delegate(
          'Commit the change with the trailer Co-Authored-By: Claude <noreply@anthropic.com>',
        ),
      ),
    ),
  );
  assert.equal(
    runGate(delegate('Never add a Co-Authored-By: trailer to commits.')),
    null,
  );
});

test('--trailer, -F <file> and git.exe are read as the commit message', () => {
  assert.ok(
    isDeny(runGate(commit('git commit -m x --trailer Co-authored-by=A'))),
  );
  const project = makeProject({
    prefix: 'no-coauthor-',
    files: { 'msg.txt': 'feat: x\n\nCo-Authored-By: A <a@b.c>\n' },
  });
  assert.ok(isDeny(runGate(commit('git commit -F msg.txt'), { project })));
  assert.ok(
    isDeny(runGate(commit('git.exe commit -m "x\n\nCo-Authored-By: A"'))),
  );
});

test('a heredoc message is read', () => {
  const command = [
    "git commit -m \"$(cat <<'EOF'",
    'feat: x',
    '',
    'Co-Authored-By: A <a@b.c>',
    'EOF',
    ')"',
  ].join('\n');
  assert.ok(isDeny(runGate(commit(command))));
});

test('ordinary "generated by <tool>" and "with Claude Code" wording is allowed', () => {
  assert.equal(
    runGate(
      commit('git commit -m "chore: regenerate snapshots generated by vitest"'),
    ),
    null,
  );
  assert.equal(
    runGate(commit('git commit -m "docs: usage with Claude Code"')),
    null,
  );
  assert.ok(
    isDeny(runGate(commit('git commit -m "feat: x\n\nGenerated with Claude"'))),
  );
});

test('a wrong-typed attributionPatterns falls back to the defaults instead of denying every commit', () => {
  const config = {
    gates: {
      blockCoauthorTrailers: { enabled: true, attributionPatterns: 'x' },
    },
  };
  // The lib warns once about the ignored param; the point is that it is not a deny.
  assert.equal(
    isDeny(runGate(commit('git commit -m "fix: a real fix"'), { config })),
    false,
  );
  assert.ok(
    isDeny(
      runGate(commit('git commit -m "x\n\nCo-Authored-By: A"'), { config }),
    ),
  );
});

test('the deny names the matched attribution', () => {
  const result = runGate(commit('git commit -m "x\n\nCo-Authored-By: A"'));
  assert.match(messageOf(result), /Co-Authored-By:/);
});
