// claude-md.mjs — writes what the ACTIVE gates expect into CLAUDE.md, so the model arrives
// already aligned instead of discovering each rule by being denied.
//
// justification: no existing tool covers this. materialize.mjs writes the gate CONFIG (what
// runs); capability-map injects the SKILL catalog into a turn's context. Neither tells the
// model how this project expects it to work, which is why the same collisions repeat: the
// model writes a test after the implementation, forgets a task's verification criterion, or
// improvises a helper — and learns the rule only from the denial.
//
// The block is GENERATED from the registry's own descriptions, never hand-written, so it
// cannot drift from the gates that are actually on. Everything outside the markers is
// preserved byte for byte: this edits a file the user owns, and a tool that mangles a
// CLAUDE.md would be worse than one that never ran.

import { existsSync, readFileSync } from 'node:fs';
import { allGates } from './registry.mjs';

export const BLOCK_START = '<!-- claude-gates:start -->';
export const BLOCK_END = '<!-- claude-gates:end -->';

const HEADING = '## How this project expects you to work';

function enabledGates(registry, gatesConfig) {
  return allGates(registry).filter((gate) => {
    const entry = gatesConfig?.[gate.configKey];
    if (entry === undefined) return gate.default;
    if (typeof entry === 'boolean') return entry;
    return entry?.enabled !== false;
  });
}

function familyLines(registry, gates) {
  const byFamily = new Map();
  for (const gate of gates) {
    if (!byFamily.has(gate.family)) byFamily.set(gate.family, []);
    byFamily.get(gate.family).push(gate);
  }
  const lines = [];
  for (const family of registry.families) {
    const members = byFamily.get(family.id);
    if (!members) continue;
    lines.push(`\n**${family.name}**\n`);
    for (const gate of members)
      lines.push(`- \`${gate.id}\` — ${gate.description}`);
  }
  return lines;
}

// Marker-delimited so that a later run replaces exactly this and nothing else, and so a
// reader can tell at a glance which part of their CLAUDE.md is generated.
export function renderBlock(registry, gatesConfig) {
  const gates = enabledGates(registry, gatesConfig);
  const body =
    gates.length === 0
      ? '\nNo gates are enabled for this project.'
      : [
          '',
          `${gates.length} gate(s) are enforcing the rules below. They are checked`,
          'deterministically before a tool call, so following them up front is cheaper than',
          'being denied and retrying.',
          ...familyLines(registry, gates),
        ].join('\n');

  return [
    BLOCK_START,
    `${HEADING}`,
    body,
    '',
    '_Generated by `claude-gates`. Edits inside these markers are overwritten; everything',
    'outside them is left untouched._',
    BLOCK_END,
  ].join('\n');
}

// Appends instead of failing when there are no markers yet, so that a first run on an
// existing CLAUDE.md never has to touch what the user already wrote.
export function mergeBlock(existing, block) {
  const text = String(existing ?? '');
  const start = text.indexOf(BLOCK_START);
  const end = text.indexOf(BLOCK_END);
  if (start === -1 || end === -1 || end < start) {
    const separator = text.trim() ? `${text.trimEnd()}\n\n` : '';
    return `${separator}${block}\n`;
  }
  return `${text.slice(0, start)}${block}${text.slice(end + BLOCK_END.length)}`;
}

export function readClaudeMd(path) {
  return existsSync(path) ? readFileSync(path, 'utf8') : '';
}
